name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_API_ID: ${{secrets.API_ID}}
          HD_API_HASH: ${{secrets.API_HASH}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_ALD_USR: ${{secrets.ALD_USR}}
          HD_BASE_URL_OF_BOT: ${{secrets.BASE_URL_OF_BOT}}
          HD_OWNER_ID: ${{secrets.OWNER_ID}}
          HD_GD_INDEX_URL: ${{secrets.GD_INDEX_URL}}
          HD_MEGA_API: ${{secrets.MEGA_API}}
          HD_MEGA_ENABLE: ${{secrets.MEGA_ENABLE}}
          HD_MEGA_PASS: ${{secrets.MEGA_PASS}}
          HD_MEGA_UNAME: ${{secrets.MEGA_UNAME}}
          HD_TG_UP_LIMIT: ${{secrets.TG_UP_LIMIT}}
          HD_QBIT_HOST: ${{secrets.QBIT_HOST}}
          HD_QBIT_PORT: ${{secrets.QBIT_PORT}}
          HD_QBIT_UNAME: ${{secrets.QBIT_UNAME}}
          HD_QBIT_PASS: ${{secrets.QBIT_PASS}}
          HD_QBIT_MAX_RETRIES: ${{secrets.QBIT_MAX_RETRIES}}
          HD_TRACKER_SOURCE: ${{secrets.TRACKER_SOURCE}}
